
project_id = "yblwafdsidkuzgzfazpf"

[storage]
[storage.buckets.avatars]
public = true

[storage.buckets.kyc_documents]
public = true

[storage.buckets.group_resources]
public = true

[storage.buckets.community_attachments]
public = true
