
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yblwafdsidkuzgzfazpf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlibHdhZmRzaWRrdXpnemZhenBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MDU2MzIsImV4cCI6MjA2MjM4MTYzMn0.5GiBnyp-NAAZbOcenQYWkqPt-x0jvOcW4InS1U-u-Ns";

// Define the site URL based on environment
const SITE_URL = process.env.NODE_ENV === 'production' 
  ? 'https://doc-know-grow-together.netlify.app' 
  : window.location.origin;

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      storageKey: 'medcollab-auth-token',
      storage: localStorage,
      detectSessionInUrl: true,
      flowType: 'pkce',
      // Define redirect URLs
      redirectTo: `${SITE_URL}/email-confirmation`
    }
  }
);

// Add a listener to log auth events during debugging
if (process.env.NODE_ENV === 'development') {
  supabase.auth.onAuthStateChange((event, session) => {
    console.log('Supabase Auth Event:', event, session ? 'Session exists' : 'No session');
  });
}
